spring:
  application:
    name: pay
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
server:
  port: 8080


# mybatis-plus配置
mybatis-plus:
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.wensheng.entity


#  appId: wx3e6b9f1c5a7ff034
#  mchId: 1614433647
#  mchKey: Aa111111111122222222223333333333
wx:
  app-id: wx3e6b9f1c5a7ff034
  mch-id: 1614433647
  mch-key: Aa111111111122222222223333333333
  notify-url: http://8fgv6m.natappfree.cc/pay/notify
  return-url: http://8fgv6m.natappfree.cc/success.html
